#PROGRAM TO DISPLAY A THE CALENDAR FOR A PARTICULAR YEAR AND MONTH
#HERE WE ARE IMPORTING CALENDAR FUNCTION
import calendar 

#WE ARE TAKING THE INPUT FROM THE USER 
year=int(input("enter the year"))
month=int(input("enter the month"))

#THIS LINE PRINTS THE CALENDAR FOR A PARTICULAR YEAR AND MONTH BY USING THE CALENDAR FUNCTION
print(calendar.month(year,month))
